Repository SFI-Visual-Intelligence/Collaborative-Coding-Exam, pull requests merged in 2025-02, with the labels that each got.

#36 Add autoapi to crawl our modules and populate the docs, closes #14
  doc/about.md
  doc/conf.py
  main.py
  utils/dataloaders/datasources.py
  utils/dataloaders/mnist_0_3.py
  utils/dataloaders/usps_0_6.py
  utils/load_data.py
  utils/load_metric.py
  utils/load_model.py
Labels: documentation

#69 Usps inputshape, resolve #67
  main.py
  utils/arg_parser.py
  utils/dataloaders/svhn.py
  utils/models/christian_model.py
Labels: enhancement

#49 Create tests for load_model/metric/data, closes #46
  .gitignore
  tests/test_dataloaders.py
  utils/dataloaders/uspsh5_7_9.py
Labels: enhancement

#83 Additional configuration files and options
  .github/workflows/test.yml
  .gitignore
  pytest.ini
Labels: enhancement

#97 Restructure tests for more intuitive structure
  CollaborativeCoding/dataloaders/mnist_4_9.py
  main.py
  tests/test_dataloaders.py
  tests/test_metrics.py
  tests/test_models.py
  tests/test_wrappers.py
Labels: enhancement

#98 Fix bug where usps test weren't able to download usps data
  CollaborativeCoding/dataloaders/download.py
  tests/test_dataloaders.py
Labels: bug

#103 Fixed a small bug in metric wrapper
  CollaborativeCoding/load_metric.py
  CollaborativeCoding/metrics/EntropyPred.py
Labels: bug

#108 Only run when modifications are done to code paths
  .github/workflows/format.yml
  .github/workflows/test.yml
Labels: enhancement

#116 Installation instructions
  README.md
Labels: documentation

#117 Github action that makes release upon new tag push
  .github/workflows/create_release.yml
Labels: enhancement

#120 Add citation, please fill your orcid if you have one
  CITATION.cff
Labels: documentation

#123 Restrict python version < 3.13 and update version
  CITATION.cff
  pyproject.toml
Labels: bug
